pipeline {
    agent {
        label 'terraform-node'
    }
    environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'ap-south-1'
    }

    stages {

        stage ('Checkout_code') {
            steps {
                git branch: 'Main', url: 'https://github.com/Abhimanyu89403/DEV.git'
            }
        }
        stage ('initiate terraform'){
                steps{
                    dir('infra/alb'){
                        bat 'dir'
                        bat 'terraform init'
                    }
                }
            }
        stage ('terraform plan'){
            steps{
                dir('infra/alb'){
                    bat 'dir'
                    bat 'terraform plan -var-file="alb.tfvars" -out=tfplan'
                }
            }
        }
        stage ('Manual approval'){
            steps {
                input message: 'Do you want to proceed?' , ok: "Yes , Apply" 
            }
        }
        

        stage ('terraform apply'){
                steps {
                    dir('infra/alb'){
                        bat 'dir'
                        bat 'terraform apply tfplan'
                    }
                }
            }  
        }
}