pipeline {
    agent any 
        environment {
            AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
            AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
            AWS_DEFAULT_REGION = 'ap-south-1'
        }
    stages {
        
        stage ('Checkout Code') {
            steps {
                git branch: 'Main', url: 'https://github.com/Abhimanyu89403/DEV.git'
            }
        }
        stage ('initiate terraform') {
            steps {
                dir('infra/vpc'){
                    bat 'dir'
                    bat 'terraform init'
                }
            }
        }
        stage ('format check') {
            steps {
                dir('infra/vpc'){
                    bat 'terraform fmt -check'
                }
            }
        }
        stage ('validate the code') {
            steps {
                dir('infra/vpc'){
                    bat 'terraform validate'
                }
            }
        }
        stage ('terraform plan') {
            steps {
                dir('infra/vpc'){
                    bat ('dir')
                    bat 'terraform plan -var-file="vpc.tfvars" -out=tfplan'
                }
            }
        }
        stage ('Manual approval') {
            steps {
                input message : "Do you want to proceed?" , ok :"Yes,  Apply"
            }
        }
        stage ('apply the architecture') {
            steps {
                dir('infra/vpc'){
                    bat 'terraform apply tfplan'
            }
        }
    }
    post {
        success {
            echo 'Infrastructure applied successfully'
        }
        failure {
            echo 'pipeline failed check logs'
        }
    }

}