pipeline {
    agent {
        label 'terraform-node'
    }

    environment{
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'ap-south-1'
    }

    stages{
        stage('Checkout code'){
            steps {
                git branch: 'Main' , url: 'https://github.com/Abhimanyu89403/DEV.git'
            }
        }
        stage('initiate terraform'){
            steps{
                dir('infra/ecs'){
                    bat 'dir'
                    bat 'terraform init'
                }
            }
        }
        stage('terraform plan'){  
            steps{
                dir('infra/ecs'){
                    bat 'dir'
                    bat 'terraform plan -var-file="prod.tfvars" -out=tfplan'
                }
            }
        }
        stage('Mannual aproval'){
            steps{
                 input message: 'Do you want to proceed?' , ok: 'yes, Apply'   
            }
        }
        stage('terraform apply'){
            steps{
                dir('infra/ecs'){
                    bat('dir')
                    bat 'terraform apply tfplan'
                }
            }
        }
    }
}